[tool.poetry]
name = "training-loop"
version = "0.1.0"
description = "Simple Keras-like Training Loop for Pytorch."
authors = ["beekill <nguyenmbquan95@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "training_loop"}]

[tool.poetry.dependencies]
python = "^3.8"
torch = { version = "*", source = "torch-cpu" }
torcheval = "*"
pandas = "*"
numpy = "*"
tqdm = "*"


[tool.poetry.group.dev.dependencies]
pytest = "^7.4.2"
pytest-mock = "^3.11.1"
pre-commit = "^3.4.0"

[[tool.poetry.source]]
name = "torch-cpu"
url = "https://download.pytorch.org/whl/cpu"
priority = "explicit"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
