[tool.poetry]
name = "torch-training-loop"
version = "0.0.0"
description = "Simple Keras-inspired Training Loop for Pytorch."
authors = ["beekill <nguyenmbquan95@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "training_loop", from = "src" }]
homepage = "https://github.com/beekill95/torch-training-loop"
repository = "https://github.com/beekill95/torch-training-loop"
classifiers = [
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Software Development",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

[tool.poetry.urls]
"CHANGELOG" = "https://github.com/beekill95/torch-training-loop/blob/main/CHANGELOG.md"

[tool.poetry.dependencies]
python = "^3.8"
torch = [
    { version = "*", source = "torch-cpu", markers = "sys_platform == 'linux'" },
    { version = "*", markers = "sys_platform == 'win32' or sys_platform == 'darwin'"  },
]
torcheval = "*"
pandas = "*"
numpy = "*"
tqdm = "*"


[tool.poetry.group.dev.dependencies]
pytest = "^7.4.2"
pytest-mock = "^3.11.1"
pre-commit = "^3.4.0"
pytest-rerunfailures = "^12.0"
tensorboard = "*"


[tool.poetry.group.examples.dependencies]
torchvision = [
    { version = "*", source = "torch-cpu", markers = "sys_platform == 'linux'" },
    { version = "*", markers = "sys_platform == 'win32' or sys_platform == 'darwin'"  },
]
jupyterlab = "^4.0.7"
jupytext = "^1.15.2"
matplotlib = "^3.6.0"

[[tool.poetry.source]]
name = "torch-cpu"
url = "https://download.pytorch.org/whl/cpu"
priority = "explicit"


[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
style = "pep440"

[tool.poetry-dynamic-versioning.substitution]
folders = [{ path = "src" }]

[tool.poetry-dynamic-versioning.files."src/training_loop/_version.py"]
persistent-substitution = true
initial-content = """
# Generated by poetry-dynamic-versioning plugin.
__version__ = "0.0.0"
__version_tuple__ = (0, 0, 0)
"""

[tool.yapf]
based_on_style = "yapf"
indent_width = "4"
column_limit = "88"

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning>=1.0.0,<2.0.0"]
build-backend = "poetry_dynamic_versioning.backend"
